account:
  uin: 123456789

message:
  post-format: string

output:
  log-level: warn
  log-aging: 1

database:
  leveldb:
    enable: false

servers:
  - ws-reverse:
      universal: ws://127.0.0.1:9304/qqbot
      reconnect-interval: 5000
