[package]
name = "ksite"
version = "0.1.1"
edition = "2021"

[profile.release]
strip = true
# panic = "abort" # DO NOT USE THIS! cause tokio worker abort

[dependencies]
axum = { version = "0.4", features = ["ws"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
reqwest = "0.11"
lazy_static = "1.4"
askama_escape = "0.10"
rusqlite = { version = "0.27.0", features = ["bundled"] }
