[package]
name = "ksite"
version = "0.1.0"
edition = "2021"

[profile.release]
# strip = true
# panic = "abort" # DO NOT USE THIS! cause tokio worker abort

[dependencies]
axum = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
reqwest = "0.11"
rusty-leveldb = "0.3"
lazy_static = "1.4"
askama_escape = "0.10"
