[package]
name = "ksite"
version = "0.5.1"
edition = "2021"

[profile.release]
# panic = "abort" # DO NOT USE THIS! cause tokio worker abort
strip = true
lto = true

# For full build speed (ci), `cargo check --profile=ci`.
[profile.ci]
inherits = "release"
opt-level = 0
lto = false
panic = "abort"
incremental = false
codegen-units = 256

# For incremental build speed and disk usage, `mold -run cargo run`.
[profile.dev]
debug = false   # this dose not affect backtrace
panic = "abort"
[profile.dev.package."*"]
strip = true
opt-level = "z"

[features]
default = ["qqbot"]
qqbot = []

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
askama_escape = "0.10"
axum = { version = "0.5", features = ["ws"] }
futures-util = "0.3"
httpdate = "1"
hyper = { version = "0.14", features = ["http2"] }
hyper-rustls = { version = "0.23", default-features = false, features = ["http1"] }
webpki-roots = "0.22"
miniz_oxide = "0.5"
once_cell = "1"
rand = "0.8"
ricq = "0.1.16" # unstable, fixed version here
rusqlite = { version = "0.28", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tokio-rustls = "0.23"
tower-http = { version = "0.3", features = ["auth"] }
# tls-listener = { version = "0.5", features = ["rustls", "hyper-h2"] }

[patch.crates-io]
ricq = { rev = "9eb56c5", git = "https://github.com/lz1998/ricq" }
futures = { path = "./src/crates/futures-fake" } # for `cached` crate, see `Cargo.lock`
prost-build = { path = "./src/crates/prost-gen" } # for `ricq-core` crate
