[package]
name = "ksite"
version = "0.4.0-alpha-2"
edition = "2021"

[profile.dev]
debug = false
strip = true

[profile.dev.package."*"]
debug = false
strip = true
opt-level = "z"

[profile.release]
strip = true
lto = "fat"
# panic = "abort" # DO NOT USE THIS! cause tokio worker abort

[dependencies]
tokio = { version = "1.18.2", features = ["macros", "rt-multi-thread"] }
axum = { version = "0.5.5", features = ["ws"] }
tower-http = { version = "0.3.3", features = ["auth"] }
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls"] }
futures-util = "0.3.21"
rusqlite = { version = "0.27.0", features = ["bundled"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
once_cell = "1.10.0"
askama_escape = "0.10.3"
rand = "0.8.5"
miniz_oxide = "0.5.1"
konst = { version = "0.2.13", features = ["rust_1_55"] }

hyper = "0.14.18"
tokio-rustls = "0.23.0"
