[package]
name = "ksite"
version = "0.4.4"
edition = "2021"

[profile.dev.package."*"]
strip = true
opt-level = "z"

[profile.dev]
debug = false # this dose not affect backtrace
panic = "abort"

[profile.release]
strip = true
lto = true
# panic = "abort" # DO NOT USE THIS! cause tokio worker abort

[features]
default = ["qqbot"]
qqbot = []

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
askama_escape = "0.10"
axum = { version = "0.5", features = ["ws"] }
const-str = "0.4.3"
futures-util = "0.3"
hyper = { version = "0.14", features = ["http2"] }
hyper-rustls = { version = "0.23", default-features = false, features = ["http1"] }
webpki-roots = "0.22"
miniz_oxide = "0.5"
once_cell = "1"
rand = "0.8"
ricq = { git = "https://github.com/lz1998/ricq", rev = "0e79315" } # unstable, fixed version here
rusqlite = { version = "0.27", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tokio-rustls = "0.23"
tower-http = { version = "0.3", features = ["auth"] }
# tls-listener = { version = "0.5", features = ["rustls", "hyper-h2"] }
