[package]
name = "ksite"
version = "0.2.3"
edition = "2021"

[profile.dev]
debug = false
strip = true

[profile.release]
strip = true
lto = "fat"
# panic = "abort" # DO NOT USE THIS! cause tokio worker abort

[dependencies]
tokio = { version = "1.18.0", features = ["macros", "rt-multi-thread"] }
axum = { version = "0.5.4", features = ["ws"] }
tower-http = { version = "0.3.1", features = ["compression-br", "auth"]}
reqwest = "0.11.10"
futures-util = "0.3.21"
rusqlite = { version = "0.27.0", features = ["bundled"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
once_cell = "1.10.0"
askama_escape = "0.10.3"
rand = "0.8.5"
