[package]
name = "ksite"
version = "0.4.0-alpha-8"
edition = "2021"

[profile.dev.package."*"]
debug = false
strip = true
opt-level = "z"

[profile.release]
strip = true
lto = "fat"
# panic = "abort" # DO NOT USE THIS! cause tokio worker abort

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
axum = { version = "0.5", features = ["ws"] }
tower-http = { version = "0.3", features = ["auth"] }
futures-util = "0.3"
reqwest = "0.11"
rusqlite = { version = "0.27", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
once_cell = "1"
askama_escape = "0.10"
rand = "0.8"
miniz_oxide = "0.5"
konst = { version = "0.2", features = ["rust_1_55"] }
# hyper = "0.14"
# tokio-rustls = "0.23"
