[package]
name = "prost-gen"
version = "0.1.0"
edition = "2021"
description = "A messy alternative to prost-build."

[profile.dev.package."*"]
strip = true
opt-level = "z"

[dependencies]
heck = "0.4"
prost-build = "0.9"
