name: CI

on: [push]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Cargo Check
        run: cargo +nightly check

      # - name: Build
      #   run: cargo +nightly build --release

      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     path: target/release/ksite
