name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
        rust: [stable]

    steps:
      - uses: actions/checkout@v2

      - name: Install MUSL Target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Run Build
        run: cargo build --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.os }}
          path: target/release/ksite*
