name: CI
on: [push, pull_request]
env:
  RUSTC_BOOTSTRAP: 1
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        run: git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY .
      - name: Rustup Show
        run: rustup show
      - name: Set Timestamps
        run: git ls-files | while read v; do touch -d $(git log -1 --format="@%ct" "$v") "$v"; done
      - name: Cache
        uses: actions/cache@v3
        with:
          path: target/
          key: ${{ runner.os }}-${{ hashFiles('Cargo.toml') }}
      - name: Cargo Check
        run: cargo check --profile=ci
